import ProvidersNextUI from "@/Providers/next.ui"
import Header from "@/components/header/header"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import localFont from "next/font/local"


import Footer from "@/components/footer/footer"
import { ClerkProvider } from "@clerk/nextjs"
import React from "react"


const surt = localFont({
  src: [
    {
      path: "../assets/fonts/HelveticaNeue-Light.woff",
      weight: "200",
      style: "normal",
    },
    {
      path: "../assets/fonts/HelveticaNeue-Medium.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/HelveticaNeue-Bold.woff",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-helvetica",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={surt.className}>
        <ClerkProvider>
          <ProvidersNextUI>
            <Header />
            {children}
            <Footer />
          </ProvidersNextUI>
        </ClerkProvider>
      </body>
    </html>
  )
}
