// Import React or Next
import React from "react"
import localFont from "next/font/local"
import "./globals.css"
import type { Metadata } from "next"

// Import Packages
import ProvidersNextUI from "@/Providers/next.ui"

// Import Components
import ReactQueryProvider from '@/Providers/query'
import Footer from "@/components/footer/footer"
import Header from "@/components/header/header"

const surt = localFont({
  src: [
    {
      path: "../assets/fonts/HelveticaNeue-Light.woff",
      weight: "200",
      style: "normal",
    },
    {
      path: "../assets/fonts/HelveticaNeue-Medium.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/HelveticaNeue-Bold.woff",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-helvetica",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en" className="dark">
      <body className={surt.className}>
        <ReactQueryProvider>
          <ProvidersNextUI>
            <Header />
            {children}
            <Footer />
          </ProvidersNextUI>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
